# Generated by Django 4.0.1 on 2022-02-22 08:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimsDataInsuredRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(auto_created=True, auto_now=True, help_text='date received ', null=True, verbose_name='date received')),
                ('claim_no', models.CharField(max_length=25, unique=True, verbose_name='claim number')),
                ('policy_no', models.CharField(max_length=25, unique=True, verbose_name='policy number')),
                ('insured', models.CharField(blank=True, help_text='Name of the insured', max_length=100, null=True, verbose_name='insured')),
                ('plate_no', models.CharField(blank=True, help_text='motor vehicle registration', max_length=8, null=True, verbose_name='no plate')),
                ('details_loss', models.TextField(blank=True, help_text='Details of loss', max_length=200, null=True, verbose_name='details of loss')),
                ('date_loss', models.DateField(blank=True, help_text='Date of the loss', null=True, verbose_name='date of loss')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='This is the date of last modification', null=True, verbose_name='Last modified')),
            ],
            options={
                'verbose_name': 'CLIENT RECORDS',
                'ordering': ['-claim_no'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(auto_created=True, auto_now=True, help_text='date received ', null=True, verbose_name='date received')),
                ('policy_no', models.CharField(max_length=25, unique=True, verbose_name='policy number')),
                ('plate_no', models.CharField(blank=True, help_text='motor vehicle registration', max_length=8, null=True, verbose_name='no plate')),
                ('claimant', models.CharField(blank=True, help_text='plaintif Name', max_length=100, null=True, verbose_name='plaintiff')),
                ('defendant', models.CharField(blank=True, help_text='defendant Name', max_length=100, null=True, verbose_name='defendant')),
                ('panel_adv', models.CharField(blank=True, help_text='panel advocate', max_length=50, null=True, verbose_name='panel advocate')),
                ('tp_adv', models.CharField(blank=True, help_text='third party advocate', max_length=50, null=True, verbose_name='T.P advocate')),
                ('action', models.CharField(blank=True, help_text='Action', max_length=30, null=True, verbose_name='action')),
                ('assign_to', models.CharField(help_text='Assign to', max_length=30, verbose_name='assing to')),
            ],
            options={
                'verbose_name': 'STATUTORY NOTICE RECORDS',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='Warrants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(auto_created=True, auto_now=True, help_text='date received ', null=True, verbose_name='date received')),
                ('execution_received', models.DateField(blank=True, help_text='date received ', null=True, verbose_name='proclamation date')),
                ('region', models.CharField(blank=True, help_text='Invesco branches', max_length=30, null=True, verbose_name='branches')),
                ('plaintiff', models.CharField(blank=True, help_text='Plaintiff Name', max_length=100, null=True, verbose_name='plaintiff')),
                ('defendant', models.CharField(blank=True, help_text='defendant name', max_length=100, null=True, verbose_name='defendant')),
                ('court_station', models.CharField(blank=True, help_text='court station', max_length=30, null=True, verbose_name='court station')),
                ('tp_adv', models.CharField(blank=True, help_text='third party advocate', max_length=30, null=True, verbose_name='T.P advocate')),
                ('panel_adv', models.CharField(blank=True, help_text='third party advocate', max_length=30, null=True, verbose_name='panel advocate')),
                ('auctioneer', models.CharField(blank=True, help_text='auctioneer name', max_length=30, null=True, verbose_name='auctioneer name')),
                ('warrant_amount', models.PositiveBigIntegerField(blank=True, help_text='warrant amount', null=True, verbose_name='warrants amount')),
                ('auctioneer_amount', models.PositiveBigIntegerField(blank=True, help_text='auctioneer fees', null=True, verbose_name='auctioneer fees')),
                ('total_amount', models.PositiveBigIntegerField(help_text='Total amount', null=True, verbose_name='total amount')),
                ('assign_to', models.CharField(blank=True, help_text='Assign To', max_length=100, null=True, verbose_name='assign to')),
                ('claim_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invescofiles.claimsdatainsuredrecords', verbose_name='claim number')),
            ],
            options={
                'verbose_name': 'WARRANT RECORDS',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='Summon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(auto_created=True, auto_now=True, help_text='date received ', null=True, verbose_name='date received')),
                ('claimant', models.CharField(blank=True, help_text='plaintif Name', max_length=100, null=True, verbose_name='plaintiff')),
                ('defendant', models.CharField(blank=True, help_text='defendant Name', max_length=100, null=True, verbose_name='defendant')),
                ('injury', models.CharField(blank=True, choices=[('TPPD', 'TPPD'), ('TPP1', 'TPP1'), ('OD', 'OD'), ('WS', 'WS')], help_text='Nature of Injury', max_length=6, null=True, verbose_name='nature of injury')),
                ('case_no', models.CharField(blank=True, help_text='case number', max_length=25, null=True, unique=True, verbose_name='case no')),
                ('station', models.CharField(blank=True, help_text='branches', max_length=30, null=True, verbose_name='court station')),
                ('tp_adv', models.CharField(blank=True, help_text='third party advocate', max_length=30, null=True, verbose_name='T.P advocate')),
                ('panel_adv', models.CharField(blank=True, help_text='panel advocate i.e. invesco Ltd advocate', max_length=30, null=True, verbose_name='panel advocate')),
                ('reserve_amount', models.PositiveBigIntegerField(help_text='Reserve amount', verbose_name='reserve amount')),
                ('instruct', models.CharField(blank=True, help_text='Instructed', max_length=50, null=True, verbose_name='instructed')),
                ('remarks', models.CharField(help_text='Remarks', max_length=50, verbose_name='remarks')),
                ('claim_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invescofiles.claimsdatainsuredrecords', verbose_name='claim number')),
            ],
            options={
                'verbose_name': 'SUMMON RECORDS',
                'ordering': ['-claim_no'],
            },
        ),
        migrations.CreateModel(
            name='OutOfCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(auto_created=True, auto_now=True, help_text='date received ', null=True, verbose_name='date received')),
                ('complaint', models.CharField(blank=True, help_text='claimant/payee', max_length=100, null=True, verbose_name='claimant')),
                ('injury', models.CharField(blank=True, choices=[('TPPD', 'TPPD'), ('TPP1', 'TPP1'), ('OD', 'OD'), ('WS', 'WS')], help_text='Nature of Injury', max_length=6, null=True, verbose_name='nature of injury')),
                ('medical_rep', models.FileField(blank=True, help_text='Medical Reports', null=True, upload_to='Medical-Reports', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='second medical report')),
                ('tp_adv', models.CharField(blank=True, help_text='third party advocate', max_length=30, null=True, verbose_name='T.P advocate')),
                ('panel_adv', models.CharField(blank=True, help_text='panel advocate i.e. invesco Ltd advocate', max_length=30, null=True, verbose_name='panel advocate')),
                ('negotiated', models.CharField(blank=True, help_text='negotiated by', max_length=100, null=True, verbose_name='negotiated by')),
                ('amount_approved', models.PositiveBigIntegerField(help_text='amount approved', verbose_name='amount approved')),
                ('amount_paid', models.PositiveBigIntegerField(help_text='amount paid', verbose_name='amount paid')),
                ('outs_balance', models.PositiveBigIntegerField(blank=True, help_text='outstanding balance', verbose_name='outstanding bal.')),
                ('claim_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invescofiles.claimsdatainsuredrecords', verbose_name='claim number')),
            ],
            options={
                'verbose_name': 'OUT OF COURT RECORDS',
                'ordering': ['-claim_no'],
            },
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(auto_created=True, auto_now=True, help_text='date received ', null=True, verbose_name='DATE RECEIVED')),
                ('case_no', models.CharField(blank=True, help_text='case number', max_length=25, null=True, verbose_name='CASE NO')),
                ('insured', models.CharField(blank=True, help_text='insured Name', max_length=100, null=True, verbose_name='DEFENDANT')),
                ('claimant', models.CharField(blank=True, help_text='Claimant Name', max_length=100, null=True, verbose_name='PLAINTIFF')),
                ('station', models.CharField(blank=True, help_text='branches', max_length=30, null=True, verbose_name='COURT STATION')),
                ('pri_decl', models.CharField(blank=True, choices=[('PRI', 'PRI'), ('DECL', 'DECL')], help_text='primary/declaratory', max_length=5, null=True, verbose_name='PRI/DECL')),
                ('total_amount', models.PositiveBigIntegerField(help_text='Total amount', null=True, verbose_name='AWARD AMOUNT')),
                ('claim_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invescofiles.claimsdatainsuredrecords', verbose_name='claim number')),
            ],
            options={
                'verbose_name': 'JUDGMENT RECORDS',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(auto_created=True, auto_now=True, help_text='date received ', null=True, verbose_name='date received')),
                ('station', models.CharField(blank=True, help_text='court station', max_length=30, null=True, verbose_name='court station')),
                ('case_no', models.CharField(blank=True, help_text='case number', max_length=25, null=True, unique=True, verbose_name='case no')),
                ('plaintiff', models.CharField(blank=True, help_text='plaintif Name', max_length=100, null=True, verbose_name='plaintiff')),
                ('defendant', models.CharField(blank=True, help_text='defendant Name', max_length=100, null=True, verbose_name='defendant')),
                ('panel_adv', models.CharField(blank=True, help_text='panel advocate i.e. invesco Ltd advocate', max_length=30, null=True, verbose_name='panel advocate')),
                ('tp_adv', models.CharField(blank=True, help_text='third party advocate', max_length=50, null=True, verbose_name='T.P advocate')),
                ('magistrate', models.CharField(blank=True, help_text='defendant Name', max_length=100, null=True, verbose_name="magistrate's name")),
                ('hearing_date', models.DateField(blank=True, help_text='date received ', null=True, verbose_name='hearing date')),
                ('bring_up_date', models.DateField(help_text='hearing up date', verbose_name='bring up date')),
                ('date_of_service', models.DateField(help_text='date of service', verbose_name='date of service')),
                ('assign_to', models.CharField(blank=True, help_text='defendant Name', max_length=100, null=True, verbose_name='assigned to')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='This is the date of last modification', null=True, verbose_name='Last modified')),
                ('remarks', models.CharField(blank=True, help_text='remarks', max_length=50, null=True, verbose_name='remarks')),
                ('claim_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invescofiles.claimsdatainsuredrecords', verbose_name='claim number')),
            ],
            options={
                'verbose_name': 'HEARING RECORDS',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='ClaimRecordsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, null=True, verbose_name='File Name')),
                ('file', models.FileField(blank=True, help_text='Upload documents', upload_to='File', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='file')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='Description of the file')),
                ('date_of_submission', models.DateTimeField(auto_now_add=True, help_text="this is date of sumbmission don't fill, auto.", null=True, verbose_name='Date of creation')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='This is the date of last modification', null=True, verbose_name='Last modified')),
                ('claim_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invescofiles.claimsdatainsuredrecords', verbose_name='claim number')),
            ],
            options={
                'verbose_name': 'SCANNED FILES',
                'ordering': ['-claim_no'],
            },
        ),
    ]
