# Generated by Django 4.0.1 on 2022-02-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invescofiles', '0002_csvfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVFile',
        ),
        migrations.AlterField(
            model_name='claimsdatainsuredrecords',
            name='policy_no',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='policy number'),
        ),
    ]
