# Generated by Django 4.0.2 on 2022-02-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invescofiles', '0003_delete_csvfile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimrecordsfiles',
            options={'ordering': ['-claim_no'], 'verbose_name': 'SCANNED FILE'},
        ),
        migrations.AlterModelOptions(
            name='claimsdatainsuredrecords',
            options={'ordering': ['-claim_no'], 'verbose_name': 'INSURED RECORD'},
        ),
        migrations.AlterModelOptions(
            name='hearing',
            options={'ordering': ['-date_received'], 'verbose_name': 'HEARING RECORD'},
        ),
        migrations.AlterModelOptions(
            name='judgement',
            options={'ordering': ['-date_received'], 'verbose_name': 'JUDGMENT RECORD'},
        ),
        migrations.AlterModelOptions(
            name='outofcourt',
            options={'ordering': ['-claim_no'], 'verbose_name': 'OUT OF COURT RECORD'},
        ),
        migrations.AlterModelOptions(
            name='statutorynotice',
            options={'ordering': ['-date_received'], 'verbose_name': 'STATUTORY NOTICE RECORD'},
        ),
        migrations.AlterModelOptions(
            name='summon',
            options={'ordering': ['-claim_no'], 'verbose_name': 'SUMMON RECORD'},
        ),
        migrations.AlterModelOptions(
            name='warrants',
            options={'ordering': ['-date_received'], 'verbose_name': 'WARRANT RECORD'},
        ),
        migrations.RemoveField(
            model_name='claimrecordsfiles',
            name='description',
        ),
        migrations.RemoveField(
            model_name='claimrecordsfiles',
            name='title',
        ),
        migrations.RemoveField(
            model_name='claimsdatainsuredrecords',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='claimsdatainsuredrecords',
            name='policy_no',
        ),
        migrations.AlterField(
            model_name='claimsdatainsuredrecords',
            name='date_received',
            field=models.DateField(blank=True, help_text='date received ', null=True, verbose_name='date received'),
        ),
    ]
